services:
  wordpress:
    image: wordpress:6.7.1-php8.3-apache
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wp
    volumes:
      - ./src:/var/www/html

  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
      - wp-db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  phpmyadmin:
    image: phpmyadmin:5.2
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: password
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    depends_on:
      - db

volumes:
  wp-db-volume: